### ISSUE TITLE
Don't crash on reload failure

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/hot#9]

**Comment by gazialankus** [comment]
Is this related? This sometimes happens and HTTP requests made after this keep waiting forever. 

```
lib\src\services\services.dart changed. Reloading server...

lib\src\services\services.dart changed. Reloading server...

vm-service: isolate(735755321)  'dev.dart:main()' has no debugger attached and is paused at exit.  Connect to Observatory at http://127.0.0.1:8181/ to debug.```

**Comment by thosakwe** [comment]
No, in these cases, your app has crashed during startup. The next version
of angel_hot will catch these errors, and print out a message.

**Comment by thosakwe** [comment]
Sorry, I'd read the title of a different e-mail, and was confused. Yes, @gazialankus, that's what this issue aims to resolve.

**Comment by thosakwe** [comment]
AFAIK, the Dart VM service does not have infrastructure available to listen for when an isolate crashes. If that were there, then `angel_hot` could catch these, and report errors.

**Comment by thosakwe** [comment]
This issue is long resolved, just forgot to close it.
